spring.profiles.active: local
spring:
  profiles:
    include:

---
spring.config.activate.on-profile: local
server:
  port: 8080
logging:
  level:
    com.revy: debug


spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
   # MariaDB
#  datasource:
#    url: jdbc:mariadb://localhost:3306/contract
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: 1234
    # H2 DB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

